# Example rendering secrets using environment variables
apiVersion: v1
data:
  .dockerconfigjson: ${{{ ENV_KUBECTL_SECRET_DOCKERCONFIGJSON }}}
kind: Secret
metadata:
  name: secret-dockerconfigjson
type: kubernetes.io/dockerconfigjson