apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-deployment
  namespace: test-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
      - env:
        - name: ENVOY_LOG_LEVEL
          value: debug
        - name: ENV_KUBECTL_ENVOY_IMAGE
          value: envoyproxy/envoy:v1.24.0
        - name: ENV_KUBECTL_ENVOY_LOG_LEVEL
          value: debug
        - name: ENV_KUBECTL_ENVOY_TEST1
          value: value1
        - name: ENV_KUBECTL_ENVOY_TEST2
          value: value2
        - name: ENV_KUBECTL_ENVOY_TEST3
          value: value3
        image: envoyproxy/envoy:v1.24.0
        name: envoy
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 250m
            memory: 250m
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /etc/envoy/envoy.yaml
          name: envoy-config
          subPath: envoy.yaml
        - mountPath: /etc/envoy/static-file.html
          name: static-file
          subPath: static-file.html
      volumes:
      - configMap:
          items:
          - key: envoy.yaml
            path: envoy.yaml
          name: envoy-config
        name: envoy-config
      - configMap:
          items:
          - key: static-file.html
            path: static-file.html
          name: envoy-config
        name: static-file
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-service
  namespace: test-namespace
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: envoy
---
apiVersion: v1
data:
  envoy.yaml: |
    static_resources:
      listeners:
        - name: listener_0
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 8080
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: ingress_http
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: local_service
                          domains: ["*"]
                          routes:
                            - match:
                                prefix: "/"
                              direct_response:
                                status: 200
                                body:
                                  filename: /etc/envoy/static-file.html
                    http_filters:
                      - name: envoy.filters.http.router
  static-file.html: |
    <html>
      <body>
        <h1> Welcome to env kubectl </h1>
        <p>This is a static file served by Envoy.</p>
      </body>
    </html>
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: test-namespace
---
apiVersion: v1
data:
  .dockerconfigjson: bXkgc2VjcmV0
kind: Secret
metadata:
  name: secret-dockerconfigjson
  namespace: test-namespace
type: kubernetes.io/dockerconfigjson

---
